name: Backup and Publish with msbuild
description: Backup running version and publish .NET project using msbuild
inputs:
  projectPath:
    description: 'Path of solution or project source code'
    required: true
    default: '.'
  destinationPath:
    description: 'Path of solution or project source code'
    required: true
    default: '.'
  appName:
    description: ''
    required: true
  devopsUser:
    description: ''
    required: true
  devopsPwd:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - shell: cmd
      run: echo "${{ github.action_path }}"
    - shell: cmd
      run: ${GITHUB_WORKSPACE}\.github\scripts\msbuild\download.bat
    - env: 
          RUN_ID: ${{ github.run_id }}
          DESTINATION_PATH: ${{ inputs.destinationPath }}
          APP_NAME: ${{ inputs.appName }}
          PROJECT_PATH: ${{ inputs.projectPath }}
          DESTINATION_USER: ${{ inputs.devopsUser }}
          DESTINATION_PWD: ${{ inputs.devopsPwd }}
          VERSION: '${{ github.ref }}.${{ github.job }}.${{ github.run_id }}'
          VERSION_FILE: "Deploy\\version.txt"
      shell: cmd
      run: ${GITHUB_WORKSPACE}\.github\scripts\msbuild\deploy.bat
      