name: Deploy Release
description: Publish Release
inputs:
  projectPath:
    description: 'Path of solution or project source code'
    required: true
    default: '.'
  destinationPath:
    description: 'Path of solution or project source code'
    required: true
    default: '.'
  server:
    description: ''
    required: true
  appName:
    description: ''
    required: true
  serviceName:
    description: ''
    required: true
  appKind:
    description: ''
    required: true
    default: 'AppWeb'
  deployOptionScript:
    description: 'Use shared folder or deployment api. Folder or Api'
    required: true
    default: 'Api'
  devopsUser:
    description: ''
    required: true
  devopsPwd:
    description: ''
    required: true
  buildConfiguration:
    description: 'Compilation configuration to use. Debug or Release are the common options'
    required: false
    default: 'Release'

runs:
  using: "composite"
  steps:
    - name: Deploy .NET Release using API
      env: 
        REPO_NAME: ${{ github.event.repository.name }}
        RUN_ID: ${{ github.run_id }}
        SERVER: ${{ inputs.server }}
        APP_NAME: ${{ inputs.appName }}
        SERVICE_NAME: ${{ inputs.serviceName }}
        DESTINATION_USER: ${{ inputs.devopsUser }}
        DESTINATION_PWD: ${{ inputs.devopsPwd }}
        KIND: ${{ inputs.appKind }}
      shell: pwsh
      if: inputs.deployOptionScript == 'Api'
      run: ${{ github.workspace }}\.github\scripts\msbuild\apiDeploy.ps1

    - name: Deploy .NET Release using Shared Folder
      env: 
        REPO_NAME: ${{ github.event.repository.name }}
        RUN_ID: ${{ github.run_id }}
        DESTINATION_PATH: ${{ inputs.destinationPath }}
        SERVER: ${{ inputs.server }}
        APP_NAME: ${{ inputs.appName }}
        SERVICE_NAME: ${{ inputs.serviceName }}
        DESTINATION_USER: ${{ inputs.devopsUser }}
        DESTINATION_PWD: ${{ inputs.devopsPwd }}
        KIND: ${{ inputs.appKind }}
      shell: cmd
      if: inputs.deployOptionScript == 'Folder'
      run: ${{ github.workspace }}\.github\scripts\msbuild\folderdeploy.bat

      