name: Backup and Publish with msbuild
description: Backup running version and publish .NET project using msbuild
inputs:
  projectPath:
    description: 'Path of solution or project source code'
    required: true
    default: '.'
  destinationPath:
    description: 'Path of solution or project source code'
    required: true
    default: '.'
  appName:
    description: ''
    required: true
  devopsUser:
    description: ''
    required: true
  devopsPwd:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    - shell: cmd
      env: 
          RUN_ID: ${{ github.run_id }}
          DESTINATION_PATH: ${{ inputs.destinationPath }}
          APP_NAME: ${{ inputs.appName }}
          DESTINATION_USER: ${{ inputs.devopsUser }}
          DESTINATION_PWD: ${{ inputs.devopsPwd }}
          VERSION_FILE: "Deploy\\version.txt"
      run: .github\deploy.bat
 
            