name: Backup and Publish with msbuild
description: Backup running version and publish .NET project using msbuild
inputs:
  projectPath:
    description: 'Path of solution or project source code'
    required: true
    default: '.'
  destinationPath:
    description: 'Path of solution or project source code'
    required: true
    default: '.'
  server:
    description: ''
    required: true
  appName:
    description: ''
    required: true
  serviceName:
    description: ''
    required: true
  appKind:
    description: ''
    required: true
    default: 'AppWeb'
  devopsUser:
    description: ''
    required: true
  devopsPwd:
    description: ''
    required: true
  buildConfiguration:
    description: 'Compilation configuration to use. Debug or Release are the common options'
    required: false
    default: 'Release'

runs:
  using: "composite"
  steps:
    - env: 
        REPO_NAME: ${{ github.event.repository.name }}
        RUN_ID: ${{ github.run_id }}
        DESTINATION_PATH: ${{ inputs.destinationPath }}
        SERVER: ${{ inputs.server }}
        APP_NAME: ${{ inputs.appName }}
        SERVICE_NAME: ${{ inputs.serviceName }}
        PROJECT_PATH: ${{ inputs.projectPath }}
        BUILD_CONFIG: ${{ inputs.buildConfiguration }}
        DESTINATION_USER: ${{ inputs.devopsUser }}
        DESTINATION_PWD: ${{ inputs.devopsPwd }}
        VERSION: '${{ github.ref }}.${{ github.job }}.${{ github.run_id }}'
        VERSION_FILE: "Deploy\\version.txt"
        KIND: ${{ inputs.appKind }}
      shell: cmd
      run: ${{ github.workspace }}\.github\scripts\msbuild\deploy.bat
      