name: Sonarqube with msbuild
description: ''
inputs:
  projectPath:
    description: 'Path of solution or project source code'
    required: true
    default: '.'
  testsAssembly:
    description: ''
    required: false
    default: '-'
  sonarUrl:
    description: 'Url of sonarqube instance'
    required: true
  sonarToken:
    description: 'Api key with access to analyze projects'
    required: true
  buildConfiguration:
    description: 'Compilation configuration to use. Debug or Release are the common options'
    required: false
    default: 'Release'
 
runs:
  using: "composite"
  steps:
    - shell: cmd
      run: echo "${{ github.action_path }}"
    - shell: cmd
      run: .\.github\scripts\msbuild\download.bat
    - shell: cmd
      env: 
          REPO_NAME: ${{ github.event.repository.name }}
          PROJECT_PATH: ${{ inputs.projectPath }}
          BUILD_CONFIG: ${{ inputs.buildConfiguration }}
          TESTS_PATH: ${{ inputs.testsAssembly }}
          SONAR_TOKEN: ${{ inputs.sonarToken }}
          SONAR_URL: ${{ inputs.sonarUrl }}
      run: .\.github\scripts\msbuild\analyze.bat
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
       SONAR_TOKEN: ${{ inputs.sonarToken }}
       SONAR_HOST_URL: ${{ inputs.sonarUrl }}
    - name: SonarQube Quality Gate Status
      shell: cmd
      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
    
      