name: Analyze and Deploy
on: [push, workflow_dispatch, workflow_call]

jobs:
  Sonarqube:
    name: Sonarqube Scan
    runs-on: ['self-hosted', 'Windows', 'X64']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: 'IRAD-SW-FACTORY/DevOps'
          ref: refs/heads/feature/refactor
          path: 'scripts'
      - shell: cmd
        run: xcopy ${{ github.workspace }}\scripts\.github\scripts ${{ github.workspace }}\.github\  /Y /E
      - name: Build .NET app
        uses: ./.github/actions/msbuild/analyze
        with:
          projectPath: 'src\NET48'
          sonarUrl: ${{ vars.SONAR_URL }}
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          sonarBasicToken: ${{ secrets.SONAR_BASIC_TOKEN }}
          testsAssembly: 'NET48.Tests\bin\Release\NET48.Tests.dll'
  DeployQA:
    name: QA Deployment
    runs-on: ['self-hosted', 'Windows', 'X64']
    needs: ['Sonarqube']
    env: 
      RUN_ID: ${{ github.run_id }}
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feature') || (startsWith(github.ref, 'refs/tags/') && !startsWith(github.ref, 'refs/tags/v'))
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: 'IRAD-SW-FACTORY/DevOps'
          ref: refs/heads/feature/refactor
          path: 'scripts'
      - shell: cmd
        run: xcopy ${{ github.workspace }}\scripts\.github\scripts ${{ github.workspace }}\.github\  /Y /E
      - name: Publish .NET app
        uses: ./.github/actions/msbuild/deploy
        with:
          projectPath: 'src\NET48'
          destinationPath: '${{ vars.QA_DEPLOY_PATH }}'
          appName: '${{ vars.APP_NAME }}'
          devopsUser: 'devops'
          devopsPwd: '${{ secrets.DEVOPSUSERPWD }}'      
          
  DeployPROD:
    name: PROD Deployment
    runs-on: ['self-hosted', 'Windows', 'X64']
    needs: ['Sonarqube']
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: 'IRAD-SW-FACTORY/DevOps'
          ref: refs/heads/feature/refactor
          path: 'scripts'
      - shell: cmd
        run: xcopy ${{ github.workspace }}\scripts\.github\scripts ${{ github.workspace }}\.github\  /Y /E
      - name: Publish .NET app
        uses: ./.github/actions/msbuild/deploy
        with:
          projectPath: 'src\NET48'
          destinationPath: '${{ vars.PROD_DEPLOY_PATH }}'
          appName: '${{ vars.APP_NAME }}'
          devopsUser: 'devops'
          devopsPwd: '${{ secrets.DEVOPSUSERPWD }}' 
  