name: Analyze and Deploy
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        default: 'qa'
        options:
          - qa
          - prod
      deployOptionScript:
        required: true
        type: choice
        default: 'Folder'
        options:
          - Folder
          - Api

jobs:
  Deploy:
    uses: ./.github/workflows/msbuild_deploy.yml
    secrets: inherit
    with:
      projectPath: 'src'
      appKind: 'AppWeb'
      deployOptionScript: ${{ inputs.deployOptionScript }}