name: Analyze and Deploy
on:
  push:
    tags:
      - '**'
    branches:
      - main
      - develop
  workflow_call:
    inputs:
      projectPath:
        required: true
        type: string
        default: '.'
      testsAssembly:
        required: false
        type: string
        default: '-'
      buildConfiguration:
        required: false
        type: string
        default: 'Release'
      appKind:
        required: true
        type: string
        default: 'AppWeb'
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        default: 'qa'
        options:
          - qa
          - prod
jobs:
  Build:
    name: Build with sonarqube Scan
    uses: ./.github/workflows/msbuild_build.yml
    secrets: inherit
    with:
      projectPath: ${{ inputs.projectPath }}
      testsAssembly: ${{ inputs.testsAssembly }}

  DeployQA:
    name: QA Deployment
    runs-on: ['self-hosted', 'Windows', 'X64']
    #needs: ['Build']
    env: 
      RUN_ID: ${{ github.run_id }}
    if: (inputs.env == 'qa' || github.ref == 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/feature') || (startsWith(github.ref, 'refs/tags/') && !startsWith(github.ref, 'refs/tags/v'))
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'IRAD-SW-FACTORY/DevOps'
          ref: refs/heads/develop
          path: 'scripts'
      - shell: cmd
        run: xcopy ${{ github.workspace }}\scripts\.github\scripts ${{ github.workspace }}\.github\scripts\  /Y /E
      - shell: cmd
        run: xcopy ${{ github.workspace }}\scripts\.github\actions ${{ github.workspace }}\.github\actions\  /Y /E
      - name: Publish .NET app
        uses: ./.github/actions/msbuild/deploy
        with:
          projectPath: ${{ inputs.projectPath }}
          destinationPath: '${{ vars.QA_DEPLOY_PATH }}'
          server: '${{ vars.QA_SERVER }}'
          appName: '${{ vars.APP_NAME }}'
          appKind: ${{ inputs.appKind }}
          devopsUser: 'devops'
          devopsPwd: '${{ secrets.DEVOPSUSERPWD }}'      
          
  DeployPROD:
    name: PROD Deployment
    runs-on: ['self-hosted', 'Windows', 'X64']
    needs: ['Build']
    if: startsWith(github.ref, 'refs/tags/v') || inputs.env == 'prod'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'IRAD-SW-FACTORY/DevOps'
          ref: refs/heads/develop
          path: 'scripts'
      - shell: cmd
        run: xcopy ${{ github.workspace }}\scripts\.github\scripts ${{ github.workspace }}\.github\scripts\  /Y /E
      - shell: cmd
        run: xcopy ${{ github.workspace }}\scripts\.github\actions ${{ github.workspace }}\.github\actions\  /Y /E
      - name: Publish .NET app
        uses: ./.github/actions/msbuild/deploy
        with:
          projectPath: ${{ inputs.projectPath }}
          destinationPath: '${{ vars.PROD_DEPLOY_PATH }}'
          server: '${{ vars.PROD_SERVER }}'
          appName: '${{ vars.APP_NAME }}'
          appKind: ${{ inputs.appKind }}
          devopsUser: 'devops'
          devopsPwd: '${{ secrets.DEVOPSUSERPWD }}'     

