name: .NET Framework msbuild
on: [push]
jobs:
  Check-Version:
    runs-on: windows-latest
    steps:
      - name: MSBuild version
        run: msbuild /version
      - name: dotnet version
        run: dotnet --version
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build .NET7
        run: dotnet build src\net7_empty\NET7.csproj
      - name: Build .NET4 app for release
        run: msbuild src\net4_empty\NET4.csproj -t:rebuild -property:Configuration=Release
