on:
    release:
      types: [published]

jobs:
  Release:
    name: Upload Released Artifacts
    runs-on: ['self-hosted', 'Windows', 'X64']
    steps:
        - id: latest_release_info
          uses: jossef/action-latest-release-info@v1.2.2
        - name: Upload asset to github release page
          id: upload-release-asset
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
            asset_path: ./Release.zip
            asset_name: Release.zip
            asset_content_type: application/zip
